apiVersion: apps/v1
kind: Deployment
metadata:
  name: domjudge-spam
  labels:
    app: domjudger
spec:
  replicas: 30
  selector:
    matchLabels:
      app: domjudger
  template:
    metadata:
      labels:
        app: domjudger
    spec:
      volumes:
        - name: goodlord
          hostPath:
            path: /sys/fs/cgroup/
            type: Directory
      containers:
      - name: domjudge
        #command: ['sudo chmod a+rx /opt/domjudge/judgehost/judgings/', '&&', '/scripts/start.sh']
        volumeMounts:
          - name: goodlord
            mountPath: /sys/fs/cgroup
        image: domjudge/judgehost:latest
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
        env:
         - name: DOMSERVER_BASEURL
           #Must edit this
           value: http://host.docker.internal:12345/
         - name: JUDGEDAEMON_USERNAME
           value: judgehost
         - name: JUDGEDAEMON_PASSWORD
           value: F1QonRrDarfwCOcr1BkNgWNeIWR5/e6O
         - name: DAEMON_ID
           value: '0'
         - name: DOMJUDGE_CREATE_WRITABLE_TEMP_DIR
           value: '1'